import sys; sys.path.insert(0, ".")
import polars as pl
exec(open("../work/v10/street.py").read().split("v = st(")[0])
W = "../work/"
sc = pl.read_parquet(W + "test_scores_stage2_v11.parquet").join(pl.read_parquet(W + "norm_test_s1.parquet", columns=["entity_id", "country"]).rename({"entity_id": "s1_id"}), on="s1_id")
x = st("test", sc, False)
s1 = pl.read_parquet(W + "norm_test_s1.parquet", columns=["entity_id", "legal"]).rename({"entity_id": "s1_id", "legal": "l1"})
q = pl.concat([pl.read_parquet(W + f"norm_test_s{i}.parquet", columns=["entity_id", "legal"]) for i in (2, 3)]).rename({"entity_id": "s23_id", "legal": "lq"})
x = x.join(s1, on="s1_id").join(q, on="s23_id")
l1, lq = pl.col("l1").fill_null(""), pl.col("lq").fill_null("")
x = x.with_columns(pl.when(l1 == lq).then(pl.lit("same")).when(l1 == "").then(pl.lit("add")).when(lq == "").then(pl.lit("drop")).otherwise(pl.lit("chg")).alias("leg"))
c = x.filter((pl.col("ov") > .34) & (pl.col("u1") == pl.col("uq")) & (pl.col("p") >= .9) & (pl.col("p2") < .75))
print(c.group_by("country", "leg").agg(pl.len(), pl.col("p2").median().round(3)).sort("country", "leg"))
print("S1 counts:", pl.read_parquet(W + "norm_test_s1.parquet", columns=["country"]).group_by("country").len().rows())
# current accepted counts per S1 for the affected France S1s (from vfix)
m = pl.read_csv(W + "probe11_fr_vfix/matching_results.tsv", separator="\t", schema_overrides={"matched_entity_ids": pl.String}).rename({"source1_entity_id": "s1_id"})
m = m.with_columns(pl.col("matched_entity_ids").fill_null("").str.split(",").list.eval(pl.element().filter(pl.element() != "")).list.len().alias("nacc"))
a = c.filter((pl.col("country") == "France") & (pl.col("leg") == "add")).group_by("s1_id").len("nadd").join(m.select("s1_id", "nacc"), on="s1_id")
def f(tp, fp, fn): return 0 if tp == 0 else 1.25 * tp / (1.25 * tp + .25 * fn + fp)
gain = sum(f(n + k, 0, 0) - f(n, 0, k) for n, k in a.select("nacc", "nadd").rows())
loss = sum(f(n, 0, 0) - f(n, k, 0) for n, k in a.select("nacc", "nadd").rows())
print(f"France add S1s {a.height}: if all true +{gain:.1f} S1-F units, if all false -{loss:.1f}")
print(a.group_by("nacc").len().sort("nacc").head(8).rows())
