exec(open("inmiss.py").read().split("print(m.group_by")[0])
sys.path.insert(0,'../business_entity_resolution'); from src.india_addr import skel
mm=m.with_columns(skel("nq").str.replace_all(" ","").alias("kq"),skel("n1").str.replace_all(" ","").alias("k1"))
mm=mm.with_columns((pl.col("kq")==pl.col("k1")).alias("keq"))
a=pl.read_parquet("v10/ac2_valid_mid.parquet",columns=["s1_id","s23_id","pr"])
x=mm.filter((pl.col("country")=="India")&(pl.col("k")=="nocand")).join(a,on=["s1_id","s23_id"],how="left")
nr=x.filter(pl.col("pr").is_null())
print(nr.group_by("keq","steq").len().sort("keq","steq"))
print(nr.filter(pl.col("keq")).select("nq","n1","aq","a1").head(15))
print(nr.filter(~pl.col("keq")).sample(15,seed=1).select("nq","n1","aq","a1"))
# ambiguity of compact skeleton among India S1 in same state (full S1 universe: train)
S=pl.read_parquet("norm_train_s1.parquet",columns=["entity_id","country","name_core","state"]).filter(pl.col("country")=="India").with_columns(skel("name_core").str.replace_all(" ","").alias("k"))
cnt=S.group_by("state","k").len("kc")
y=nr.filter(pl.col("keq")).join(cnt,left_on=["stq","kq"],right_on=["state","k"],how="left")
print(y["kc"].value_counts().sort("kc").head(10))
