import sys; sys.path.insert(0,".")
import polars as pl
from src.blocking import _frames
from src.config import is_valid_expr
from src.prune import load_ground_truth
s1,q=_frames("train")
gt=load_ground_truth()
s1i=s1.select(pl.col("s1_row").cast(pl.UInt32),pl.col("entity_id").alias("s1_id"),"country",pl.col("addr_core").alias("a1"),pl.col("name_core").alias("n1"))
qi=q.select(pl.col("q_row").cast(pl.UInt32),pl.col("entity_id").alias("s23_id"),pl.col("addr_core").alias("aq"),pl.col("name_core").alias("nq"))
n1=pl.read_parquet("../work/norm_train_s1.parquet")
print(n1.columns)
vs=n1.rename({"entity_id":"s1_id"}).filter(is_valid_expr()).select("s1_id")
g=gt.join(vs,on="s1_id").join(s1i,on="s1_id").join(qi,on="s23_id")
cand=pl.read_parquet("../work/cand_train.parquet").select("q_row","s1_row").with_columns(pl.lit(1).alias("inc"))
pr=pl.read_parquet("../work/pruned_train.parquet").select("q_row","s1_row").with_columns(pl.lit(1).alias("inp"))
g=g.join(cand,on=["q_row","s1_row"],how="left").join(pr,on=["q_row","s1_row"],how="left")
g=g.with_columns((pl.col("aq").str.len_chars()==0).alias("q_empty"),(pl.col("a1").str.len_chars()==0).alias("s1_empty"))
print(len(g))
print(g.group_by("country","q_empty","s1_empty").agg(pl.len(),pl.col("inc").is_null().sum().alias("miss_cand"),pl.col("inp").is_null().sum().alias("miss_pruned")).sort("country","q_empty","s1_empty"))
m=g.filter(pl.col("inc").is_null())
pl.Config.set_tbl_rows(40); pl.Config.set_fmt_str_lengths(50)
print(m.sample(25,seed=1).select("country","n1","a1","nq","aq"))
cnt=s1i.group_by("country","n1").agg(pl.len().alias("n_same"))
e=g.filter(pl.col("q_empty")).join(cnt,on=["country","n1"],how="left")
e=e.with_columns((pl.col("n1")==pl.col("nq")).alias("exact"))
print(e.group_by("country","exact",pl.col("inp").is_null().alias("miss")).agg(pl.len(),pl.col("n_same").median().alias("med_same"),(pl.col("n_same")==1).mean().alias("uniq")).sort("country","exact","miss"))
# how many S1 share exact name with the empty query (candidate multiplicity)
qn=qi.join(q.select(pl.col("q_row").cast(pl.UInt32),"country"),on="q_row").filter(pl.col("aq").str.len_chars()==0)
qc=qn.join(cnt.rename({"n1":"nq"}),on=["country","nq"],how="left")
print("all empty queries (train split):",qc.group_by("country").agg(pl.len(),pl.col("n_same").is_null().mean().alias("no_exact"),(pl.col("n_same")==1).mean().alias("one"),(pl.col("n_same")<=5).mean().alias("le5")))
